### ISSUE TITLE
sample template

### ISSUE THREAD

**Issue by sharkymark** [coder/coder-logstream-kube#1]
I was testing `coder-logstream-kube` last night so wrote a sample template

For some reason on the Coder installation I have on Kubernetes, the coder service account did not have enough permissions to create a workspace deployment (`kubernetes_pod` cannot be used yet/now)

The `README.md` gives `kubectl` commands to create a role and rolebinding to fix it.  Again it may have been my Coder install which dates back to summer of 2022 when our helm chart was not mature yet. Who knows.

https://github.com/sharkymark/v2-templates/tree/main/logstream-kube

@kylecarbs I do have one question, as you can see in the UI logs, all it shows is the pod is created successfully on the node. You can see when the `startup_script` starts. Should I have seen more info, like container creating? The `coder-logstream-kube` `README.md` shows more info like container creation.

<img width="1081" alt="image" src="https://github.com/coder/coder-logstream-kube/assets/2022166/7706b916-9114-4e70-b006-dceb8406ee3e">

**Comment by ericpaulsen** [comment]
@sharkymark i also tested last night - our current Helm chart only provides permissions for creating `pods` and `persistentvolumeclaims`. i don't think adding `deployment.apps` is necessary at this point (the less amount of privileges, the better).

@kylecarbs i tested with your `kyle-testing` template in dogfood, and am not seeing the logs populate in the UI:


<img width="1418" alt="Screenshot 2023-05-23 at 9 09 06 AM" src="https://github.com/coder/coder-logstream-kube/assets/9683576/8dda082c-c13f-456d-8c78-4401a0bf3302">

**Comment by sreya** [comment]
I'm not sure how relevant this issue is anymore so I'm closing. The helm chart seems to work fine for me.
