### ISSUE TITLE
This logstream pod seems to restart periodically

### ISSUE THREAD

**Issue by bpmct** [coder/coder-logstream-kube#11]
On @sharkymark's cluster, the logstream pod seems to restart periodically. It still sends logs, but doesn't seem to run for a long time.

We were able to find some logs from GCP. The format isn't great but there are definitely errors which causes the container to exit and restart:

**Comment by bpmct** [comment]
[logstream-coder-oss-demo-2-coder-demo-1-downloaded-logs-20230817-194647.json.zip](https://github.com/coder/coder-logstream-kube/files/12374392/logstream-coder-oss-demo-2-coder-demo-1-downloaded-logs-20230817-194647.json.zip)

**Comment by sharkymark** [comment]
Thanks @bpmct - it happens on an EKS and GKE deployment. Both are on `0.0.7` but I've been experiencing these pod restarts for over a month.

**Comment by sreya** [comment]
Should be fixed by https://github.com/coder/coder-logstream-kube/pull/16
