### ISSUE TITLE
Streaming other events

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder-logstream-kube#13]
We're using this and it works great!

We'd like to extend it to capture events from spot instance interruptions on underlying hosts. We already have another service that determines that.

Just wondering if you think this would be possible how I would need to format the event to coder to capture it and associate it with that users workspace.

**Comment by dcarrion87** [comment]
Nevermind just realised we can patch into https://harrison-coder.harrison.ts.net/api/v2/workspaceagents/me/startup-logs with the workspace agent token. Which looks like is exactly what the coder logstream stuff is doing.

**Comment by sreya** [comment]
Closing since it seems like you have a solution already :slightly_smiling_face:
