### ISSUE TITLE
Build executable for ARM64

### ISSUE THREAD

**Issue by flipperdolphin** [coder/coder-logstream-kube#29]
Would it be possible to build the executable with support for ARM64? 

Trying to use it on an ARM node at the minute exits with `exec /coder-logstream-kube: exec format error`

**Comment by matifali** [comment]
cc: @sreya, @kylecarbs

**Comment by matifali** [comment]
Going to give it a try.

**Comment by flipperdolphin** [comment]
Thanks for looking at this quickly! Just confirmed this is working nicely on my ARM nodes. :relaxed:

**Comment by matifali** [comment]
@flipperdolphin [`v0.0.11`](https://github.com/coder/coder-logstream-kube/releases/tag/v0.0.11) is published and includes publishing a multi-arch image. Thanks for confirming that it works as expected.
