### ISSUE TITLE
workspaceagents endpoint not found with coder 1.13.0

### ISSUE THREAD

**Issue by alexander-dammeier** [coder/coder-logstream-kube#30]
Hi,

we tested coder-logstream-kube with a coder 2.13.0 instance. It worked fine prior to the this update with coder 2.12.x in the same cluster. Our test environment uses envbox templates.

Could this be related to the removal of the agents v1 API endpoints (and be a bug in coder as v2-api is clearly called here)? 

```
2024-07-15 11:04:32.437 [warn]  coder-username-test-5fbd78556d: upload startup logs failed  error="PATCH https://mydomain.com/api/v2/workspaceagents/me/startup-logs: unexpected status code 404: Route not found."  count=4
```
This log message appears every 5 seconds.

**Comment by f0ssel** [comment]
Looks like this is related to the v1 api endpoints removal and need to be updated to v2.1. 

We need to replace the usage of the old agent client https://github.com/coder/coder-logstream-kube/blob/2c028003920418b1bb9438fee989aadf52c71311/logger.go#L307-L308 with the new drpc based client.

**Comment by coadler** [comment]
https://github.com/coder/coder-logstream-kube/releases/tag/v0.0.10
